# This travis file relis on the following environment variable to configure on your travis repository settings:
# * DOCKERHUB_USER: A docker hub user where images will be pushed
# * DOCKERHUB_PASS: The password of the dockerhub user
# * DOCKERHUB_REPO: The docker repository to push to

language: minimal
services:
  - docker

stages:
    - buildtest
    - name: makedocker
      if: tag IS present
    - name: makedockermanifest
      if: tag IS present

jobs:
  include:
    - stage: buildtest
      script: ./Build/buildtest.sh
    - stage: makedocker
      env: DOCKERFILE=amd64.Dockerfile ARCH=amd64
      script: ./Build/makedocker.sh
    -
      env: DOCKERFILE=arm32v7.Dockerfile ARCH=arm32v7
      script: ./Build/makedocker.sh
    -
      env: DOCKERFILE=arm64v8.Dockerfile ARCH=arm64v8
      script: ./Build/makedocker.sh
    - stage: makedockermanifest
      script: ./Build/makedockermanifest.sh
