# This travis file relis on the following environment variable to configure on your travis repository settings:
# * DOCKER_USERNAME: A docker hub user where images will be pushed
# * DOCKER_API_KEY: The password of the dockerhub user
# * DOCKERHUB_REPO: The docker repository to push to

name: Docker

# Controls when the action will run. 
on:
  push:
    tags:
      - 'releases/*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  DOCKERHUB_USER: nicolasdorier
  DOCKERHUB_REPO: ndlc-cli

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  amd64:
    name: Build/Push amd64
    runs-on: ubuntu-latest
    env:
      DOCKERFILE: amd64.Dockerfile
      ARCH: amd64
    steps:
      - uses: actions/checkout@v2
      - run: ./Build/makedocker.sh
        env:
          DOCKER_API_KEY: ${{ secrets.DOCKER_API_KEY }}
  arm32:
    name: Build/Push arm32v7
    runs-on: ubuntu-latest
    env:
      DOCKERFILE: arm32v7.Dockerfile
      ARCH: arm32v7
    steps:
      - uses: actions/checkout@v2
      - run: ./Build/makedocker.sh
        env:
          DOCKER_API_KEY: ${{ secrets.DOCKER_API_KEY }}
  arm64v8:
    name: Build/Push arm64v8
    runs-on: ubuntu-latest
    env:
      DOCKERFILE: arm64v8.Dockerfile
      ARCH: arm64v8
    steps:
      - uses: actions/checkout@v2
      - run: ./Build/makedocker.sh
        env:
          DOCKER_API_KEY: ${{ secrets.DOCKER_API_KEY }}
  manifest:
    name: "Create docker manifest"
    runs-on: ubuntu-latest
    needs: [amd64, arm32, arm64v8]
    if: ${{ success() }}
    steps:
      - uses: actions/checkout@v2
      - run: ./Build/makedockermanifest.sh
        env:
          DOCKER_API_KEY: ${{ secrets.DOCKER_API_KEY }}
